apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    node.environment=development
    http-server.http.port=8081
    query.max-memory=1GB
    query.max-memory-per-node=512MB
    discovery.uri=http://trino:8081
  jvm.config: |
    -server
    -Xmx4G
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
data:
  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://iceberg-rest:8181
    iceberg.rest-catalog.warehouse=s3://warehouse/
    iceberg.file-format=PARQUET
    # hive.s3.endpoint=http://minio:9000
    # hive.s3.path-style-access=true
    #hive.s3.aws-access-key=admin
    #hive.s3.aws-secret-key=password
