image:
  repository: quay.io/zagaos/iceberg-custom-rest
  tag: "1.0"
  pullPolicy: IfNotPresent

containerPort: 8181

env:
  AWS_ACCESS_KEY_ID: minioAdmin
  AWS_SECRET_ACCESS_KEY: minio1234
  AWS_REGION: us-east-1
  CATALOG_WAREHOUSE: s3://warehouse/
  CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
  CATALOG_S3_ENDPOINT: http://minio:9000
  CATALOG_CATALOG__IMPL: org.apache.iceberg.jdbc.JdbcCatalog
  CATALOG_URI: jdbc:postgresql://postgres:5432/iceberg_metadata
  CATALOG_JDBC_USER: iceberg_user
  CATALOG_JDBC_PASSWORD: iceberg_pass
  CATALOG_JDBC_DRIVER: org.postgresql.Driver
  REST_PORT: "8181"

service:
  type: ClusterIP
  port: 8181

postgresql:
  enabled: false
