apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dataproduct
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rest
spec:
  selector:
    app: {{ .Release.Name }}-rest
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
