apiVersion: v1
kind: ConfigMap
metadata:
  name: data-product-config
data:
  config.json: |
    {
        "caseURL" : "https://dataproduct-client-api-dataproduct.apps.zagaopenshift.zagaopensource.com/"
    }
