apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-catalog-ui
  labels:
    app: iceberg-catalog-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-catalog-ui
  template:
    metadata:
      labels:
        app: iceberg-catalog-ui
    spec:
      containers:
      - name: iceberg-catalog-ui
        image: quay.io/zagaos/dataproduct-dashboard:v11
        # command: [ "npm", "run", "dev" ]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config
          name: data-product-cm
      volumes:
      - name: data-product-cm
        configMap:
          defaultMode: 420
          name: data-product-config
