apiVersion: v1
kind: Service
metadata:
  name: iceberg-catalog-ui
spec:
  selector:
    app: iceberg-catalog-ui
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort  # Or LoadBalancer if needed in cloud
