image:
  repository: trinodb/trino
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

env:
  - name: TRINO_USER
    value: "admin"
  - name: TRINO_CATALOG
    value: "iceberg"

resources: {}
