replicaCount: 1

image:
  repository: "quay.io/osclimate/postgresql-13"
  tag: "1-101"

strategy:
  type: {}

service:
  type: ClusterIP

securityContext: {}

secretEnv:
  data:
      POSTGRES_USER: iceberg_user
      POSTGRES_PASSWORD: iceberg_pass
      POSTGRES_DB: iceberg_metadata
      
  type: Opaque

volumes:
  storageSize: 2Gi
  accessModes:
    - ReadWriteOnce

casemanagedb:
  enabled: true