apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataproduct-client-api
  labels:
    app: dataproduct-client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataproduct-client-api
  template:
    metadata:
      labels:
        app: dataproduct-client-api
    spec:
      containers:
      - name: dataproduct-client-api
        image: quay.io/zagaos/dataproduct-client-api:v3
        command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
        workingDir: /app
        ports:
        - containerPort: 8000
        env:
        - name: TRINO_USER
          value: "admin"
        - name: TRINO_CATALOG
          value: "iceberg"
        - name: TRINO_HOST
          value: "http://trino:8080"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "iceberg_user"
        - name: POSTGRES_PASSWORD
          value: "iceberg_pass"
        - name: POSTGRES_DB
          value: "postgres"
        - name: BASE_URL
          value: "http://127.0.0.1:8000/"
      #   volumeMounts:
      #   - name: app-code
      #     mountPath: /app
      # volumes:
      # - name: app-code
      #   hostPath:
      #     path: ./dataproduct-client-api/app
      #     type: Directory
