apiVersion: v1
kind: Service
metadata:
  name: dataproduct-client-api
spec:
  selector:
    app: dataproduct-client-api
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8000
  type: ClusterIP # Use ClusterIP if internal-only; LoadBalancer for cloud
